using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class FollowPlayer : MonoBehaviour {
 
	public Transform Player;
	[SerializeField]
	int MoveSpeed = 4;
	[SerializeField]
	int MaxDist = 10;
	[SerializeField]
	int MinDist = 5;
 
 
	void Update()
	{
		transform.LookAt(Player);
 
		if (Vector3.Distance(transform.position, Player.position) >= MinDist)
		{
 
			transform.position += transform.forward * MoveSpeed * Time.deltaTime;
 
 
 
			if (Vector3.Distance(transform.position, Player.position) <= MaxDist)
			{
				//Here Call any function U want Like Shoot at here or something
			}
 
		}
	}
}
